/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import rojerusan.RSNotifyAnimated;

/**
 *
 * @author JoelDc
 */
public class View extends javax.swing.JFrame {

    /**
     * Creates new form View
     */
    public View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelButtons = new javax.swing.JPanel();
        btnNO = new javax.swing.JButton();
        BtnSI = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Para Larecy con mucho cariño");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe Script", 1, 30)); // NOI18N
        jLabel1.setText("¿Quieres estar conmigo?");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/amor-romantico-pareja-linda_24640-51122.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 260, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 100));
        jPanel1.getAccessibleContext().setAccessibleName("La Pregunta");

        jPanelButtons.setBackground(new java.awt.Color(255, 255, 255));
        jPanelButtons.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnNO.setFont(new java.awt.Font("Kristen ITC", 1, 20)); // NOI18N
        btnNO.setText("Nel Prro");
        btnNO.setToolTipText("");
        btnNO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.white, java.awt.Color.orange, null, null));
        btnNO.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNOMouseEntered(evt);
            }
        });
        jPanelButtons.add(btnNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 140, 50));

        BtnSI.setFont(new java.awt.Font("Kristen ITC", 1, 20)); // NOI18N
        BtnSI.setText("Obvis");
        BtnSI.setToolTipText("");
        BtnSI.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, java.awt.Color.pink, java.awt.Color.darkGray));
        BtnSI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSIActionPerformed(evt);
            }
        });
        jPanelButtons.add(BtnSI, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, 130, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/gato.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        jPanelButtons.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, -360, 350, 620));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/152780319_2097788127030077_6149416360140474194_n.jpg"))); // NOI18N
        jPanelButtons.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 210));

        getContentPane().add(jPanelButtons, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 630, 260));

        getAccessibleContext().setAccessibleDescription("<3");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNOMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNOMouseEntered
       int btnNOWidth = jPanelButtons.getWidth()-btnNO.getWidth();
       int btnNOHeight = jPanelButtons.getHeight()-btnNO.getHeight();
       int x = (int)Math.round(btnNOWidth*Math.random());
       int y = (int)Math.round(btnNOHeight*Math.random());
       btnNO.setLocation(x, y);
    }//GEN-LAST:event_btnNOMouseEntered

    private void BtnSIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSIActionPerformed
        RSNotifyAnimated notify = new RSNotifyAnimated("TANTO LO PENSASTE MRD!!", "Fue una forma de mostrarte que eres una chica muy linda con muchas cosas positivas", 15, RSNotifyAnimated.PositionNotify.TopLef, RSNotifyAnimated.AnimationNotify.UpBottom, RSNotifyAnimated.TypeNotify.WARNING);
        notify.setVisible(true);
    }//GEN-LAST:event_BtnSIActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnSI;
    private javax.swing.JButton btnNO;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelButtons;
    // End of variables declaration//GEN-END:variables
}
